//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Core.API.EntityModel
{
    public partial class APM_MASTER__DISTRIBUTION
    {
        public int InvoiceID { get; set; }
        public int DistSeq { get; set; }
        public Nullable<int> ConnectionID { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Description { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Tax_Group { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<double> Tax_Liability { get; set; }
        public Nullable<double> Discount_Offered { get; set; }
        public Nullable<double> Retainage { get; set; }
        public Nullable<double> Misc_Deduction { get; set; }
        public Nullable<double> Misc_Deduction2_Percent { get; set; }
        public Nullable<bool> Exempt_1099 { get; set; }
        public string Authorization { get; set; }
        public string Joint_Payee { get; set; }
        public string Dist_Code { get; set; }
        public string Expense_Account { get; set; }
        public string Accounts_Payable_Account { get; set; }
        public string Job { get; set; }
        public string Extra { get; set; }
        public string Cost_Code { get; set; }
        public string Category { get; set; }
        public string Commitment { get; set; }
        public Nullable<int> Commitment_Line_Item { get; set; }
        public Nullable<double> Units { get; set; }
        public Nullable<double> Unit_Cost { get; set; }
        public string Draw { get; set; }
        public string Standard_Item { get; set; }
        public string Equipment { get; set; }
        public string Cost_Code_295 { get; set; }
        public string Misc_Entry_1 { get; set; }
        public Nullable<double> Misc_Entry_Units_1 { get; set; }
        public string Misc_Entry_2 { get; set; }
        public Nullable<double> Misc_Entry_Units_2 { get; set; }
        public Nullable<double> MeterOdometer { get; set; }
        public string PM_Tenant { get; set; }
        public string PM_Lease { get; set; }
        public Nullable<short> PM_Lease_Revision_Num { get; set; }
        public string PM_Property { get; set; }
        public string PM_Unit { get; set; }
        public string PM_Charge_Type { get; set; }
        public Nullable<System.DateTime> PM_Charge_Date { get; set; }
        public string PM_Item_ID { get; set; }
        public string PM_Chargeback_Description { get; set; }
        public Nullable<double> PM_Markup_Percent { get; set; }
        public Nullable<double> PM_Markup_Amount { get; set; }
        public string PM_Markup_Charge_Type { get; set; }
        public string Operator_Stamp { get; set; }
        public Nullable<System.DateTime> Date_Stamp { get; set; }
    }
    
}
