//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Core.API.EntityModel
{
    public partial class APM_MASTER__INVOICE
    {
        public int InvoiceID { get; set; }
        public Nullable<int> ConnectionID { get; set; }
        public bool Deleted { get; set; }
        public string Vendor { get; set; }
        public string Invoice { get; set; }
        public string Description { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<double> Discount_Offered { get; set; }
        public Nullable<double> Misc_Deduction { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
        public Nullable<System.DateTime> Date_Received { get; set; }
        public Nullable<System.DateTime> Discount_Date { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public Nullable<System.DateTime> Accounting_Date { get; set; }
        public string Invoice_Code_1 { get; set; }
        public string Invoice_Code_2 { get; set; }
        public string Smry_Payee_Name { get; set; }
        public string Smry_Payee_Address_1 { get; set; }
        public string Smry_Payee_Address_2 { get; set; }
        public string Smry_Payee_City { get; set; }
        public string Smry_Payee_State { get; set; }
        public string Smry_Payee_ZIP { get; set; }
        public string Operator_Stamp { get; set; }
        public Nullable<System.DateTime> Date_Stamp { get; set; }
        public Nullable<int> POHeaderID { get; set; }
    }
    
}
