//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Core.API.EntityModel
{
    public partial class APM_MASTER__TAX_DISTRIBUTION
    {
        public int InvoiceID { get; set; }
        public int DistSeq { get; set; }
        public int TaxSeq { get; set; }
        public int ImportTaxSeq { get; set; }
        public Nullable<int> ConnectionID { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Tax_Item { get; set; }
        public Nullable<double> Tax_Amount { get; set; }
        public Nullable<double> Tax_Liability { get; set; }
        public string Operator_Stamp { get; set; }
        public Nullable<System.DateTime> Date_Stamp { get; set; }
    }
    
}
