//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace Core.API.EntityModel
{
    public partial class CoreAPIEntities : DbContext
    {
        public CoreAPIEntities()
            : base("name=CoreAPIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<APM_MASTER__DISTRIBUTION> APM_MASTER__DISTRIBUTION { get; set; }
        public DbSet<APM_MASTER__INVOICE> APM_MASTER__INVOICE { get; set; }
        public DbSet<APM_MASTER__TAX_DISTRIBUTION> APM_MASTER__TAX_DISTRIBUTION { get; set; }
        public DbSet<tblAccrual> tblAccruals { get; set; }
        public DbSet<tblAccrualSetting> tblAccrualSettings { get; set; }
        public DbSet<tblAction> tblActions { get; set; }
        public DbSet<tblApprovalGroupItem> tblApprovalGroupItems { get; set; }
        public DbSet<tblApprovalGroupMember> tblApprovalGroupMembers { get; set; }
        public DbSet<tblApprovalGroup> tblApprovalGroups { get; set; }
        public DbSet<tblAutoApproveAccount> tblAutoApproveAccounts { get; set; }
        public DbSet<tblAutoApproveVendor> tblAutoApproveVendors { get; set; }
        public DbSet<tblConfiguration> tblConfigurations { get; set; }
        public DbSet<tblConnection> tblConnections { get; set; }
        public DbSet<tblExistingInvoice> tblExistingInvoices { get; set; }
        public DbSet<tblGLAccount> tblGLAccounts { get; set; }
        public DbSet<tblInvoiceAction> tblInvoiceActions { get; set; }
        public DbSet<tblInvoiceCode> tblInvoiceCodes { get; set; }
        public DbSet<tblInvoiceNote> tblInvoiceNotes { get; set; }
        public DbSet<tblInvoice> tblInvoices { get; set; }
        public DbSet<tblInvoices_Custom_Fields> tblInvoices_Custom_Fields { get; set; }
        public DbSet<tblPrefixVendorJob> tblPrefixVendorJobs { get; set; }
        public DbSet<tblUserPermission> tblUserPermissions { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
        public DbSet<tblUsersConfiguration> tblUsersConfigurations { get; set; }
        public DbSet<tblVersion> tblVersions { get; set; }
        public DbSet<TSErrorLog> TSErrorLogs { get; set; }
        public DbSet<tblUserGroup> tblUserGroups { get; set; }
        public DbSet<tblUserGroupMember> tblUserGroupMembers { get; set; }
    }
}
