//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Core.API.EntityModel
{
    public partial class tblApprovalGroupMember
    {
        public int ConnectionID { get; set; }
        public string MemberType { get; set; }
        public string MemberValue { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string ProcessingGroupID { get; set; }
        public int ItemID { get; set; }
    }
    
}
