//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Core.API.EntityModel
{
    public partial class tblApprovalGroupItem
    {
        public int ItemID { get; set; }
        public int ConnectionID { get; set; }
        public string MemberType { get; set; }
        public string MemberValue { get; set; }
        public bool Selected { get; set; }
        public string Key1 { get; set; }
        public string Key2 { get; set; }
        public string Key3 { get; set; }
        public string Key4 { get; set; }
        public string Description { get; set; }
        public string ProjectManager { get; set; }
    }
    
}
