//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Core.API.EntityModel
{
    public partial class tblApprovalGroup
    {
        public int GroupID { get; set; }
        public string ProcessingGroupID { get; set; }
        public Nullable<int> RejectProcessingGroupID { get; set; }
        public string GroupName { get; set; }
        public string APVendUserID { get; set; }
        public string Action01 { get; set; }
        public Nullable<int> GroupID01 { get; set; }
        public string UserID01 { get; set; }
        public Nullable<double> Threshold01 { get; set; }
        public string Action02 { get; set; }
        public Nullable<int> GroupID02 { get; set; }
        public string UserID02 { get; set; }
        public Nullable<double> Threshold02 { get; set; }
        public string Action03 { get; set; }
        public Nullable<int> GroupID03 { get; set; }
        public string UserID03 { get; set; }
        public Nullable<double> Threshold03 { get; set; }
        public string Action04 { get; set; }
        public Nullable<int> GroupID04 { get; set; }
        public string UserID04 { get; set; }
        public Nullable<double> Threshold04 { get; set; }
        public string Action05 { get; set; }
        public Nullable<int> GroupID05 { get; set; }
        public string UserID05 { get; set; }
        public Nullable<double> Threshold05 { get; set; }
        public string Action06 { get; set; }
        public Nullable<int> GroupID06 { get; set; }
        public string UserID06 { get; set; }
        public Nullable<double> Threshold06 { get; set; }
        public string Action07 { get; set; }
        public Nullable<int> GroupID07 { get; set; }
        public string UserID07 { get; set; }
        public Nullable<double> Threshold07 { get; set; }
        public string Action08 { get; set; }
        public Nullable<int> GroupID08 { get; set; }
        public string UserID08 { get; set; }
        public Nullable<double> Threshold08 { get; set; }
        public string Action09 { get; set; }
        public Nullable<int> GroupID09 { get; set; }
        public string UserID09 { get; set; }
        public Nullable<double> Threshold09 { get; set; }
        public string Action10 { get; set; }
        public Nullable<int> GroupID10 { get; set; }
        public string UserID10 { get; set; }
        public Nullable<double> Threshold10 { get; set; }
        public int InvoiceCompleteLevel { get; set; }
    }
    
}
