//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Core.API.EntityModel
{
    public partial class tblAccrualSetting
    {
        public int ConnectionID { get; set; }
        public Nullable<bool> AccrueJobCost { get; set; }
        public string JCCompleteInvoices { get; set; }
        public string JCIncompleteInvoices { get; set; }
        public string JCDefJob { get; set; }
        public string JCDefCostCode { get; set; }
        public string JCDefCategory { get; set; }
        public string JCDebitAccount { get; set; }
        public string JCCreditAccount { get; set; }
        public Nullable<bool> AccrueOverhead { get; set; }
        public string OHCompleteInvoices { get; set; }
        public string OHIncompleteInvoices { get; set; }
        public string OHDebitPrefix { get; set; }
        public string OHDebitAccount { get; set; }
        public string OHCreditPrefix { get; set; }
        public string OHCreditAccount { get; set; }
        public Nullable<int> OHAccrualJournal { get; set; }
        public Nullable<int> OHReversalJournal { get; set; }
        public Nullable<System.DateTime> LastAccrualDate { get; set; }
        public Nullable<bool> CloseAccoutingDate { get; set; }
        public string Reference1Type { get; set; }
        public string Reference1 { get; set; }
        public string Reference2Type { get; set; }
        public string Reference2 { get; set; }
        public Nullable<System.DateTime> AccrualPeriod { get; set; }
        public string CurrentAction { get; set; }
    }
    
}
