//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Core.API.EntityModel
{
    public partial class tblAction
    {
        public int ID { get; set; }
        public string Action1 { get; set; }
        public string Action2 { get; set; }
        public string Action3 { get; set; }
        public string Action4 { get; set; }
        public string Action5 { get; set; }
        public string Action6 { get; set; }
        public string Action7 { get; set; }
        public string Action8 { get; set; }
        public string Action9 { get; set; }
        public string Action10 { get; set; }
    }
    
}
