//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Core.API.EntityModel
{
    public partial class tblAutoApproveVendor
    {
        public int ConnectionID { get; set; }
        public string Vendor { get; set; }
        public Nullable<bool> AutoApproveRecur { get; set; }
        public Nullable<bool> AutoApproveRegular { get; set; }
        public Nullable<double> ApprovalThresholdRecur { get; set; }
        public Nullable<double> ApprovalThresholdRegular { get; set; }
    }
    
}
