//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Core.API.EntityModel
{
    public partial class tblConfiguration
    {
        public tblConfiguration()
        {
            this.tblUsersConfigurations = new HashSet<tblUsersConfiguration>();
        }
    
        public int ConfigurationID { get; set; }
        public string ConfigurationName { get; set; }
        public string ConfigurationDescription { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<tblUsersConfiguration> tblUsersConfigurations { get; set; }
    }
    
}
