//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Core.API.EntityModel
{
    public partial class tblConnection
    {
        public int ConnectionID { get; set; }
        public string Description { get; set; }
        public string Path { get; set; }
        public string SystemType { get; set; }
        public Nullable<bool> DefaultConnection { get; set; }
        public string PrefixADesc { get; set; }
        public string PrefixABDesc { get; set; }
        public string PrefixABCDesc { get; set; }
        public Nullable<int> JobSec1Size { get; set; }
        public string JobPunct1 { get; set; }
        public Nullable<int> JobSec2Size { get; set; }
        public string JobPunct2 { get; set; }
        public Nullable<int> JobSec3Size { get; set; }
        public Nullable<int> CostCodeSec1Size { get; set; }
        public string CostCodePunct1 { get; set; }
        public Nullable<int> CostCodeSec2Size { get; set; }
        public string CostCodePunct2 { get; set; }
        public Nullable<int> CostCodeSec3Size { get; set; }
        public string CostCodePunct3 { get; set; }
        public Nullable<int> CostCodeSec4Size { get; set; }
        public Nullable<System.DateTime> LastApproveImportedDate { get; set; }
        public Nullable<System.DateTime> LastApproveRMDate { get; set; }
        public Nullable<System.DateTime> LastApproveRecurringDate { get; set; }
        public Nullable<System.DateTime> LastApproveRegularDate { get; set; }
        public string Alias { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
    
}
