//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Core.API.EntityModel
{
    public partial class tblInvoiceNote
    {
        public int ConnectionID { get; set; }
        public int InvoiceID { get; set; }
        public int Sequence { get; set; }
        public string NoteType { get; set; }
        public string ActionType { get; set; }
        public Nullable<short> ActionLevel { get; set; }
        public string Priority { get; set; }
        public Nullable<System.DateTime> NoteDate { get; set; }
        public string Operator { get; set; }
        public string NoteText { get; set; }
        public byte[] RwVersion { get; set; }
    }
    
}
