//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Core.API.EntityModel
{
    public partial class tblInvoiceAction
    {
        public int ActionID { get; set; }
        public Nullable<int> ConnectionID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<int> ProcessGroupID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string ActionType { get; set; }
        public Nullable<short> ActionLevel { get; set; }
        public Nullable<bool> Hold { get; set; }
        public Nullable<bool> Rejected { get; set; }
        public Nullable<bool> Complete { get; set; }
        public string CompletedBy { get; set; }
        public Nullable<System.DateTime> DateAssigned { get; set; }
        public string AssignedBy { get; set; }
        public Nullable<System.DateTime> DateComplete { get; set; }
        public string Comment { get; set; }
        public string ActionSource { get; set; }
    }
    
}
