//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Core.API.EntityModel
{
    public partial class tblUser
    {
        public string UserID { get; set; }
        public int UserIDNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string email { get; set; }
        public string NotificationMethod { get; set; }
        public bool UserLoggedOn { get; set; }
        public bool AccountEnabled { get; set; }
        public bool Administrator { get; set; }
        public bool Supervisor { get; set; }
        public bool EnterVendors { get; set; }
        public bool EnterInvoices { get; set; }
        public bool PrintInvoices { get; set; }
        public bool UploadInvoices { get; set; }
        public bool ReviewInvoices { get; set; }
        public bool FinalReview { get; set; }
        public bool RecurringInvoices { get; set; }
        public bool RescannedInvoices { get; set; }
        public bool RejectInvoice { get; set; }
        public bool RouteInvoicePreAprv { get; set; }
        public bool RouteInvoicePostAprv { get; set; }
        public bool ChangeInvoices { get; set; }
        public bool ImportInvoices { get; set; }
        public bool ApproveInvoices { get; set; }
        public bool ApproveLowerInvoices { get; set; }
        public bool AttachChecks { get; set; }
        public bool DeleteInvoices { get; set; }
        public bool ProcessRejects { get; set; }
        public bool JointChecks { get; set; }
        public bool Exempt1099 { get; set; }
        public bool EmailSystem { get; set; }
        public bool MessageSystem { get; set; }
        public bool ReviewPaidInvoices { get; set; }
        public Nullable<int> SignatureSize { get; set; }
        public byte[] Signature { get; set; }
        public Nullable<int> CheckInterval { get; set; }
        public Nullable<int> NotificationTimeout { get; set; }
        public string BalloonTipTitle { get; set; }
        public bool ToDoList { get; set; }
        public bool AddNewCodes { get; set; }
        public bool ChangeType { get; set; }
        public bool Inquiries { get; set; }
        public bool ViewAll { get; set; }
        public string Password { get; set; }
        public bool AddImages { get; set; }
        public bool RemoveImages { get; set; }
        public bool ChangeDistributions { get; set; }
        public bool VendorHistory { get; set; }
        public bool RegularInquiries { get; set; }
        public bool JobCostInquiries { get; set; }
        public bool Annotations { get; set; }
        public bool AllowHoldInAP { get; set; }
        public bool VendorInquiries { get; set; }
        public bool ChangeInvoiceAmount { get; set; }
        public bool BlackBerryActive { get; set; }
        public string DeviceId { get; set; }
        public int BBDataEntryGroup { get; set; }
        public bool AIMAcquire { get; set; }
        public bool AIMEntry { get; set; }
        public bool AIMSearch { get; set; }
        public bool AIMEditDocument { get; set; }
        public bool InvoiceOnHold { get; set; }
        public int SebringUserId { get; set; }
        public string SavedPathRgI { get; set; }
        public string SavedPathEI { get; set; }
        public string SavedPathC { get; set; }
        public string SavedPathII { get; set; }
        public string SavedPathIUFA { get; set; }
        public string SavedPathRcI { get; set; }
        public string SavedPathSD { get; set; }
        public string SavedPathAD { get; set; }
        public string SavedPathCF { get; set; }
        public bool AIMViewAll { get; set; }
        public bool Duplex { get; set; }
        public bool RetainImageSize { get; set; }
        public Nullable<bool> ProcessCapturedInvoices { get; set; }
        public string OCRUserSettings { get; set; }
        public Nullable<bool> AutoDeskew { get; set; }
        public Nullable<bool> AutoDeskewAlways { get; set; }
        public bool ApproveDocuments { get; set; }
        public bool AIMRouteOnFly { get; set; }
        public bool AIMOverrideRoute { get; set; }
        public bool AttachSDInApproval { get; set; }
        public bool AttachSDInFinalReview { get; set; }
        public bool ShowThumbnails_IE { get; set; }
        public bool DoNotShowMessageAboutThumbnails_IE { get; set; }
        public bool ShowThumbnails_PI { get; set; }
        public bool DoNotShowMessageAboutThumbnails_PI { get; set; }
        public bool ShowThumbnails_EI { get; set; }
        public bool DoNotShowMessageAboutThumbnails_EI { get; set; }
        public bool ShowThumbnails_ACM { get; set; }
        public bool DoNotShowMessageAboutThumbnails_ACM { get; set; }
        public bool ShowThumbnails_AAC { get; set; }
        public bool DoNotShowMessageAboutThumbnails_AAC { get; set; }
        public bool ShowThumbnails_SD { get; set; }
        public bool DoNotShowMessageAboutThumbnails_SD { get; set; }
        public bool ImportPO { get; set; }
        public bool AIMAddTiffPages { get; set; }
        public bool AIMDeleteDoc { get; set; }
        public bool IEOverride { get; set; }
        public string LoginCount { get; set; }
        public Nullable<bool> IsMobileUser { get; set; }
        public byte[] RwVersion { get; set; }
    }
    
}
