//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Core.API.EntityModel
{
    public partial class TSErrorLog
    {
        public int ErrorLogID { get; set; }
        public string ScreenName { get; set; }
        public string FunctionName { get; set; }
        public string Exception { get; set; }
        public string InnerException { get; set; }
        public string ErrMessage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUserID { get; set; }
    }
    
}
