//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.2045
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.API.Services.Test.ConfigSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConfigSvc.IConfig")]
    public interface IConfig {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfig/configuration", ReplyAction="http://tempuri.org/IConfig/configurationResponse")]
        string configuration();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfig/headerconfiguration", ReplyAction="http://tempuri.org/IConfig/headerconfigurationResponse")]
        string headerconfiguration();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfig/distributionconfiguration", ReplyAction="http://tempuri.org/IConfig/distributionconfigurationResponse")]
        string distributionconfiguration();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConfigChannel : Core.API.Services.Test.ConfigSvc.IConfig, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfigClient : System.ServiceModel.ClientBase<Core.API.Services.Test.ConfigSvc.IConfig>, Core.API.Services.Test.ConfigSvc.IConfig {
        
        public ConfigClient() {
        }
        
        public ConfigClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConfigClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string configuration() {
            return base.Channel.configuration();
        }
        
        public string headerconfiguration() {
            return base.Channel.headerconfiguration();
        }
        
        public string distributionconfiguration() {
            return base.Channel.distributionconfiguration();
        }
    }
}
