//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3662
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class TimberScanSettings {
    
    private string importedInvoicesField;
    
    private string tLPasswordField;
    
    private string captureRejectFolderField;
    
    private string oSSupport64BitField;
    
    private string passwordField;
    
    private string approvalStampField;
    
    private string receivingTicketField;
    
    private string autoApproveAllInvoicesField;
    
    private string attachChecksField;
    
    private string tScanMobileServerField;
    
    private string aPInvoiceUserIDField;
    
    private string tSyncDriverField;
    
    private string serverRequiresAuthenticationField;
    
    private string systemIDField;
    
    private string rejectMethodField;
    
    private string mailPortField;
    
    private string autoApprovalVendorsField;
    
    private string jCSystemField;
    
    private string captureHotFolderField;
    
    private string reviewMandatoryField;
    
    private string tLUserIDField;
    
    private string autoStampApprovalField;
    
    private string lastOtherInvoiceProcessDateField;
    
    private string subFolderType2DescField;
    
    private string notifyUserOfBccField;
    
    private string userMessageField;
    
    private string tScanMobilePasswordField;
    
    private string omitAcctNameField;
    
    private string sQLConnectMethodField;
    
    private string recurringInvoiceAttachmentsField;
    
    private string aPDatabaseField;
    
    private string tScanServer64Field;
    
    private string autoApprovalAccountsField;
    
    private string masterEMailAddressField;
    
    private string checkImageFolderField;
    
    private string invoicesWithDataField;
    
    private string invoiceCode1SelectField;
    
    private string masterEMailFromField;
    
    private string reviewEntryMandatoryField;
    
    private string blankPageToleranceField;
    
    private string captureImportFolderField;
    
    private string checkSubFolderType1Field;
    
    private string aPInvoicesServerField;
    
    private string recurringInvoicesField;
    
    private string attachPaidChecksField;
    
    private string mDBVersionField;
    
    private string updateTimberlineField;
    
    private string groupPrefixField;
    
    private string dateReceivedUsageField;
    
    private string subFolderType1Field;
    
    private string subFolderType2Field;
    
    private string approvalDateField;
    
    private string tScanMobileDriverField;
    
    private string eSMTPAuthModeField;
    
    private string tScanMobileUserIDField;
    
    private string tSyncServer64Field;
    
    private string aPInvoicePasswordField;
    
    private string useCommitmentItemDescField;
    
    private string sourceDirectoryField;
    
    private string tSyncUserIDField;
    
    private string recurringAutoApprovalVendorsField;
    
    private string totalActionsField;
    
    private string captureProcessedFolderField;
    
    private string alwaysBatchExportField;
    
    private string multiDataFolderEntryField;
    
    private string sQLAuthenticationField;
    
    private string pMSystemField;
    
    private string tSyncServerField;
    
    private string imageQualityField;
    
    private string recurringAutoApprovalAccountsField;
    
    private string sMTPServerField;
    
    private string invoiceRoutingField;
    
    private string invoiceFolderField;
    
    private string autoStampLocationField;
    
    private string tScanMobileServer64Field;
    
    private string storeCheckImagesField;
    
    private string adminPasswordField;
    
    private string signatureTypeField;
    
    private string tSyncPasswordField;
    
    private string budgetVarianceCheckField;
    
    private string subFolderType1DescField;
    
    private string bccEMailAddress1Field;
    
    private string tScanMobileDatabaseField;
    
    private string bccEMailAddress2Field;
    
    private string uploadDirectoryField;
    
    private string loginField;
    
    private string checkSubFolderType2Field;
    
    private string tSyncDatabaseField;
    
    private string setupCompleteField;
    
    private string approvalSignatureField;
    
    private string interfaceTransInvoicesField;
    
    private string tScanSyncDriver64Field;
    
    private string aPInvoicesDriverField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ImportedInvoices {
        get {
            return this.importedInvoicesField;
        }
        set {
            this.importedInvoicesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TLPassword {
        get {
            return this.tLPasswordField;
        }
        set {
            this.tLPasswordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CaptureRejectFolder {
        get {
            return this.captureRejectFolderField;
        }
        set {
            this.captureRejectFolderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OSSupport64Bit {
        get {
            return this.oSSupport64BitField;
        }
        set {
            this.oSSupport64BitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ApprovalStamp {
        get {
            return this.approvalStampField;
        }
        set {
            this.approvalStampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReceivingTicket {
        get {
            return this.receivingTicketField;
        }
        set {
            this.receivingTicketField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AutoApproveAllInvoices {
        get {
            return this.autoApproveAllInvoicesField;
        }
        set {
            this.autoApproveAllInvoicesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AttachChecks {
        get {
            return this.attachChecksField;
        }
        set {
            this.attachChecksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TScanMobileServer {
        get {
            return this.tScanMobileServerField;
        }
        set {
            this.tScanMobileServerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string APInvoiceUserID {
        get {
            return this.aPInvoiceUserIDField;
        }
        set {
            this.aPInvoiceUserIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TSyncDriver {
        get {
            return this.tSyncDriverField;
        }
        set {
            this.tSyncDriverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServerRequiresAuthentication {
        get {
            return this.serverRequiresAuthenticationField;
        }
        set {
            this.serverRequiresAuthenticationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SystemID {
        get {
            return this.systemIDField;
        }
        set {
            this.systemIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RejectMethod {
        get {
            return this.rejectMethodField;
        }
        set {
            this.rejectMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MailPort {
        get {
            return this.mailPortField;
        }
        set {
            this.mailPortField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AutoApprovalVendors {
        get {
            return this.autoApprovalVendorsField;
        }
        set {
            this.autoApprovalVendorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string JCSystem {
        get {
            return this.jCSystemField;
        }
        set {
            this.jCSystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CaptureHotFolder {
        get {
            return this.captureHotFolderField;
        }
        set {
            this.captureHotFolderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReviewMandatory {
        get {
            return this.reviewMandatoryField;
        }
        set {
            this.reviewMandatoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TLUserID {
        get {
            return this.tLUserIDField;
        }
        set {
            this.tLUserIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AutoStampApproval {
        get {
            return this.autoStampApprovalField;
        }
        set {
            this.autoStampApprovalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LastOtherInvoiceProcessDate {
        get {
            return this.lastOtherInvoiceProcessDateField;
        }
        set {
            this.lastOtherInvoiceProcessDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SubFolderType2Desc {
        get {
            return this.subFolderType2DescField;
        }
        set {
            this.subFolderType2DescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NotifyUserOfBcc {
        get {
            return this.notifyUserOfBccField;
        }
        set {
            this.notifyUserOfBccField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UserMessage {
        get {
            return this.userMessageField;
        }
        set {
            this.userMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TScanMobilePassword {
        get {
            return this.tScanMobilePasswordField;
        }
        set {
            this.tScanMobilePasswordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OmitAcctName {
        get {
            return this.omitAcctNameField;
        }
        set {
            this.omitAcctNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SQLConnectMethod {
        get {
            return this.sQLConnectMethodField;
        }
        set {
            this.sQLConnectMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RecurringInvoiceAttachments {
        get {
            return this.recurringInvoiceAttachmentsField;
        }
        set {
            this.recurringInvoiceAttachmentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string APDatabase {
        get {
            return this.aPDatabaseField;
        }
        set {
            this.aPDatabaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TScanServer64 {
        get {
            return this.tScanServer64Field;
        }
        set {
            this.tScanServer64Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AutoApprovalAccounts {
        get {
            return this.autoApprovalAccountsField;
        }
        set {
            this.autoApprovalAccountsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MasterEMailAddress {
        get {
            return this.masterEMailAddressField;
        }
        set {
            this.masterEMailAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CheckImageFolder {
        get {
            return this.checkImageFolderField;
        }
        set {
            this.checkImageFolderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InvoicesWithData {
        get {
            return this.invoicesWithDataField;
        }
        set {
            this.invoicesWithDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InvoiceCode1Select {
        get {
            return this.invoiceCode1SelectField;
        }
        set {
            this.invoiceCode1SelectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MasterEMailFrom {
        get {
            return this.masterEMailFromField;
        }
        set {
            this.masterEMailFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReviewEntryMandatory {
        get {
            return this.reviewEntryMandatoryField;
        }
        set {
            this.reviewEntryMandatoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BlankPageTolerance {
        get {
            return this.blankPageToleranceField;
        }
        set {
            this.blankPageToleranceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CaptureImportFolder {
        get {
            return this.captureImportFolderField;
        }
        set {
            this.captureImportFolderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CheckSubFolderType1 {
        get {
            return this.checkSubFolderType1Field;
        }
        set {
            this.checkSubFolderType1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string APInvoicesServer {
        get {
            return this.aPInvoicesServerField;
        }
        set {
            this.aPInvoicesServerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RecurringInvoices {
        get {
            return this.recurringInvoicesField;
        }
        set {
            this.recurringInvoicesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AttachPaidChecks {
        get {
            return this.attachPaidChecksField;
        }
        set {
            this.attachPaidChecksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MDBVersion {
        get {
            return this.mDBVersionField;
        }
        set {
            this.mDBVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UpdateTimberline {
        get {
            return this.updateTimberlineField;
        }
        set {
            this.updateTimberlineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GroupPrefix {
        get {
            return this.groupPrefixField;
        }
        set {
            this.groupPrefixField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DateReceivedUsage {
        get {
            return this.dateReceivedUsageField;
        }
        set {
            this.dateReceivedUsageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SubFolderType1 {
        get {
            return this.subFolderType1Field;
        }
        set {
            this.subFolderType1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SubFolderType2 {
        get {
            return this.subFolderType2Field;
        }
        set {
            this.subFolderType2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ApprovalDate {
        get {
            return this.approvalDateField;
        }
        set {
            this.approvalDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TScanMobileDriver {
        get {
            return this.tScanMobileDriverField;
        }
        set {
            this.tScanMobileDriverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ESMTPAuthMode {
        get {
            return this.eSMTPAuthModeField;
        }
        set {
            this.eSMTPAuthModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TScanMobileUserID {
        get {
            return this.tScanMobileUserIDField;
        }
        set {
            this.tScanMobileUserIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TSyncServer64 {
        get {
            return this.tSyncServer64Field;
        }
        set {
            this.tSyncServer64Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string APInvoicePassword {
        get {
            return this.aPInvoicePasswordField;
        }
        set {
            this.aPInvoicePasswordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UseCommitmentItemDesc {
        get {
            return this.useCommitmentItemDescField;
        }
        set {
            this.useCommitmentItemDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SourceDirectory {
        get {
            return this.sourceDirectoryField;
        }
        set {
            this.sourceDirectoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TSyncUserID {
        get {
            return this.tSyncUserIDField;
        }
        set {
            this.tSyncUserIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RecurringAutoApprovalVendors {
        get {
            return this.recurringAutoApprovalVendorsField;
        }
        set {
            this.recurringAutoApprovalVendorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TotalActions {
        get {
            return this.totalActionsField;
        }
        set {
            this.totalActionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CaptureProcessedFolder {
        get {
            return this.captureProcessedFolderField;
        }
        set {
            this.captureProcessedFolderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AlwaysBatchExport {
        get {
            return this.alwaysBatchExportField;
        }
        set {
            this.alwaysBatchExportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MultiDataFolderEntry {
        get {
            return this.multiDataFolderEntryField;
        }
        set {
            this.multiDataFolderEntryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SQLAuthentication {
        get {
            return this.sQLAuthenticationField;
        }
        set {
            this.sQLAuthenticationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PMSystem {
        get {
            return this.pMSystemField;
        }
        set {
            this.pMSystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TSyncServer {
        get {
            return this.tSyncServerField;
        }
        set {
            this.tSyncServerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ImageQuality {
        get {
            return this.imageQualityField;
        }
        set {
            this.imageQualityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RecurringAutoApprovalAccounts {
        get {
            return this.recurringAutoApprovalAccountsField;
        }
        set {
            this.recurringAutoApprovalAccountsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SMTPServer {
        get {
            return this.sMTPServerField;
        }
        set {
            this.sMTPServerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InvoiceRouting {
        get {
            return this.invoiceRoutingField;
        }
        set {
            this.invoiceRoutingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InvoiceFolder {
        get {
            return this.invoiceFolderField;
        }
        set {
            this.invoiceFolderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AutoStampLocation {
        get {
            return this.autoStampLocationField;
        }
        set {
            this.autoStampLocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TScanMobileServer64 {
        get {
            return this.tScanMobileServer64Field;
        }
        set {
            this.tScanMobileServer64Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StoreCheckImages {
        get {
            return this.storeCheckImagesField;
        }
        set {
            this.storeCheckImagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AdminPassword {
        get {
            return this.adminPasswordField;
        }
        set {
            this.adminPasswordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SignatureType {
        get {
            return this.signatureTypeField;
        }
        set {
            this.signatureTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TSyncPassword {
        get {
            return this.tSyncPasswordField;
        }
        set {
            this.tSyncPasswordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BudgetVarianceCheck {
        get {
            return this.budgetVarianceCheckField;
        }
        set {
            this.budgetVarianceCheckField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SubFolderType1Desc {
        get {
            return this.subFolderType1DescField;
        }
        set {
            this.subFolderType1DescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BccEMailAddress1 {
        get {
            return this.bccEMailAddress1Field;
        }
        set {
            this.bccEMailAddress1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TScanMobileDatabase {
        get {
            return this.tScanMobileDatabaseField;
        }
        set {
            this.tScanMobileDatabaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BccEMailAddress2 {
        get {
            return this.bccEMailAddress2Field;
        }
        set {
            this.bccEMailAddress2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UploadDirectory {
        get {
            return this.uploadDirectoryField;
        }
        set {
            this.uploadDirectoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CheckSubFolderType2 {
        get {
            return this.checkSubFolderType2Field;
        }
        set {
            this.checkSubFolderType2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TSyncDatabase {
        get {
            return this.tSyncDatabaseField;
        }
        set {
            this.tSyncDatabaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SetupComplete {
        get {
            return this.setupCompleteField;
        }
        set {
            this.setupCompleteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ApprovalSignature {
        get {
            return this.approvalSignatureField;
        }
        set {
            this.approvalSignatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InterfaceTransInvoices {
        get {
            return this.interfaceTransInvoicesField;
        }
        set {
            this.interfaceTransInvoicesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TScanSyncDriver64 {
        get {
            return this.tScanSyncDriver64Field;
        }
        set {
            this.tScanSyncDriver64Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string APInvoicesDriver {
        get {
            return this.aPInvoicesDriverField;
        }
        set {
            this.aPInvoicesDriverField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private TimberScanSettings[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TimberScanSettings")]
    public TimberScanSettings[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
