//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.2045
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.API.Services.Test.UserSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserSvc.IUsers")]
    public interface IUsers {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/groups", ReplyAction="http://tempuri.org/IUsers/groupsResponse")]
        string groups(long version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/groupsall", ReplyAction="http://tempuri.org/IUsers/groupsallResponse")]
        string groupsall();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/groupmembership", ReplyAction="http://tempuri.org/IUsers/groupmembershipResponse")]
        string groupmembership(int groupid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/groupmembershipbyrwversion", ReplyAction="http://tempuri.org/IUsers/groupmembershipbyrwversionResponse")]
        string groupmembershipbyrwversion(long version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/groupmembershipall", ReplyAction="http://tempuri.org/IUsers/groupmembershipallResponse")]
        string groupmembershipall();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/users", ReplyAction="http://tempuri.org/IUsers/usersResponse")]
        string users(long version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/usersall", ReplyAction="http://tempuri.org/IUsers/usersallResponse")]
        string usersall();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/permission", ReplyAction="http://tempuri.org/IUsers/permissionResponse")]
        string permission(long version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/permissionall", ReplyAction="http://tempuri.org/IUsers/permissionallResponse")]
        string permissionall();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsersChannel : Core.API.Services.Test.UserSvc.IUsers, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsersClient : System.ServiceModel.ClientBase<Core.API.Services.Test.UserSvc.IUsers>, Core.API.Services.Test.UserSvc.IUsers {
        
        public UsersClient() {
        }
        
        public UsersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string groups(long version) {
            return base.Channel.groups(version);
        }
        
        public string groupsall() {
            return base.Channel.groupsall();
        }
        
        public string groupmembership(int groupid) {
            return base.Channel.groupmembership(groupid);
        }
        
        public string groupmembershipbyrwversion(long version) {
            return base.Channel.groupmembershipbyrwversion(version);
        }
        
        public string groupmembershipall() {
            return base.Channel.groupmembershipall();
        }
        
        public string users(long version) {
            return base.Channel.users(version);
        }
        
        public string usersall() {
            return base.Channel.usersall();
        }
        
        public string permission(long version) {
            return base.Channel.permission(version);
        }
        
        public string permissionall() {
            return base.Channel.permissionall();
        }
    }
}
